---
title: "Oxyegn Model"
author: "this is my name"
date: "this is the date of today"
output: html_document
---



## Loading libraries
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages(c("readr", "tidyverse", "patchwork"))
library(tidyverse)
library(patchwork)
library(openair)
```



## (1) Load the data
```{r eval=TRUE, echo = TRUE, error=FALSE, warning=FALSE, message=FALSE}

# If you're using Rstudio, change to current directory
setwd(dirname(rstudioapi::getSourceEditorContext()$path))

doObs = read_tsv("Data/Mendota.doobs")
doObs$DO[doObs$DO == 0] <- NA # masking suspicious data

wtr = read_tsv("Data/Mendota.wtr")
PAR = read_tsv("Data/Mendota.par") %>% mutate(PAR = as.numeric(PAR)) #dataset has non-numeric characters

# Now lets plot the data quickly
p1 = ggplot(doObs) + geom_line(aes(x = dateTime, y = DO)) + ylab('DO (mg/L)')
p2 = ggplot(wtr) + geom_line(aes(x = dateTime, y = temp0.5)) + ylab('Water temp 0.5 m (degC)')
p3 = ggplot(PAR) + geom_line(aes(x = dateTime, y = PAR)) + ylab('PAR')
# patchwork plots
print(p1 / p2 / p3 & theme_bw())

# Let's join the data, so we have one dataframe
in.data = doObs %>% left_join(PAR) %>% left_join(wtr)

print(head(in.data))
```

## (2) Make a simple regression model
```{r eval=TRUE, echo = TRUE, error=FALSE, warning=FALSE, message=FALSE}
# Plot DO as a function of T, just to show it
p4 = ggplot(in.data, aes(x = temp0.5, y = DO)) + 
  geom_point(size = 1) +
  geom_smooth(method = 'lm') + 
  xlab('Water temp 0.5 m (degC)') + ylab('DO (mg/L)') +
  theme_bw()
print(p4) # You have to print since these are in a loop 

```



## (3) Parameterize the model
```{r eval=TRUE, echo = TRUE, error=FALSE, warning=FALSE, message=FALSE}
## Model simulation of epilimnetic lake metabolism for Lake Mendota
## Observational data from NTL LTER

# O2 Model: dO2/dt = NPP - Rtot + Fatm
# O2(t) = O2(t-1) + (NPP(t-1) - Rtot(t-1) + Fatm(t-1)) * dt

# Phytoplankton Model: dPhyto/dt = NPP - RPhyto - Settling
# Phyto(t) = Phyto(t-1) + (NPP(t-1) - RPhyto(t-1) - Settling(t-1)) * dt

# NPP = f(PAR,phosphorus)
# Rtot = RDOC + RPhyto; RDOC = f(DOC); RPhyto = f(Phyto)
# Settling = f(zMix,Phyto)


# What data do we actually want to use in the model?
# Create vectors
wTemp = wtr$temp0.5 # water temperature at 0.5 m depth
PAR = PAR$PAR       # Photosynthetically Active Radiation (PAR) at the water surface
```



## (4) Setup constants and parameters
```{r eval=TRUE, echo = TRUE, error=FALSE, warning=FALSE, message=FALSE}
# These three constants you might normally get from observational data
phosphorus =  # Constant value of phosphorus (ug/L)
DOC =   # Constant value for dissolved organic carbon (mg/L)
zMix =   # Constant depth of the lake's upper mixed layer (m)

# Model parameters
# Fatm = k * (DO deviation from saturation) / mixed layer
kDO =    # Parameter, gas exchange piston velocity (meters/day), often calculated from, e.g., wind speed

# NPP = PAR * P * pNPP * Theta^Temperature
pNPP =   # Parameter, converts light and phosphorus to NPP (mgC/unitP/unitLight)
thetaNPP =  # Parameter, Arrhenius coefficient for temperature adjustment for NPP

# RPhyto = Phyto * phytoR * Theta^Temperature
phytoR =    # Parameter, 1st order decay of phytoplankton
thetaR =   # Parameter, Arrhenius coefficient for temperature adjustment for respiration

# SettlingPhyto = Phyto * settlingPhyto / zMix
settlingPhyto =  # Parmaeter, Settling in m/d

# RDOC = DOC * docR
docR =   # Parameter, 1st order decay of DOC

# Other necessary constants for the model
CtoO2 =  # Convert C values to DO values

```



## (5) Initializing the model
```{r eval=TRUE, echo = TRUE, error=FALSE, warning=FALSE, message=FALSE}
dt = 1/48     # Model time step (day fraction); 1/48 = 30 minutes; for now, has to be synchronized with 30 min met data
nSteps = 10500   # Known apriori (number of records in the series)

# Setup variables to track states and fluxes
# Initialize values for state variables
doPredic = doObs$DO[1] # Set the first value to the first observed value
phyto = 0.1 # g/m3

# Initializing values for fluxes
fatm = NA_real_ # Initialize atmospheric exchange
npp = NA_real_ # Initialize primary production
RDOC = NA_real_  # Initialize respiration
Rphyto = NA_real_  # Initialize respiration
Rtot = NA_real_  # Initialize respiration
dosat = NA_real_ # Initialize DO at saturation
Settling = NA_real_ # Initialize Settling of phyto


```



## (6) Run the model after filling in the equations
```{r eval=TRUE, echo = TRUE, error=FALSE, warning=FALSE, message=FALSE}
# Cycle through the model with 48 time steps per day (i.e., every 30 min)
for(i in 2:nSteps){
  # if water temp is missing, use previous value
  if(is.na(wTemp[i])){
    wTemp[i] = wTemp[i-1]
  }
  # if PAR is missing, use previous value
  if(is.na(PAR[i])){
    PAR[i] = PAR[i-1]
  }
  
  # Calculate the saturation value of dissolved oxygen as a function of temperature 
  dosat[i] = 
  
  # Atmospheric exchange
  # Fatm = k * (DO deviation from saturation) / mixed layer
  fatm[i] =  # units: m/d * g/m3 * 1/m should be mg/L/30min 
  
  # Primary production
  # NPP = PAR * P * pNPP * Theta^Temperature
  npp[i] = 
  
  # Respiration terms
  # RDOC = [DOC] * docR
  RDOC[i] = 
  # RPhyto = Phyto * phytoR * Theta^Temperature
  Rphyto[i] = 
  Rtot[i] = 
  
  # SettlingPhyto = Phyto * settlingPhyto/zMix
  Settling[i] = 
  
  # Mass balance equation for dissolved oxygen
  doPredic[i] = 
  # Mass balance equaation for phytos
  phyto[i] = 
}

# Make dataframe of output vectors 
out.model = doObs %>% slice(1:nSteps) %>% 
  mutate(doPredic = doPredic,
         phyto = phyto,
         fatm = fatm, 
         npp = npp, 
         RDOC = RDOC, 
         Rphyto = Rphyto, 
         Rtot = Rtot, 
         dosat = dosat)

# Let's calculate daily averages
out.model$date <- as.Date(out.model$dateTime)
out.model_daily <- openair::timeAverage(mydata = out.model, avg.time = "day", statistic = "mean")
out.model_daily_sum <- openair::timeAverage(mydata = out.model[,c("date","npp","Rtot","fatm")], avg.time = "day", statistic = "sum")


# Let's take a look at the modelled data!
head(out.model)

```



## (7) Plot results
```{r echo = F, fig.cap = 'modelled DO'}
# There are many ways to do this in ggplot. Ideally you'd want to convert the dataframes from wide to long, but the code below uses the wide format

# Plot the predictions at 30min scale
p5 = ggplot(out.model) +
  geom_line(aes(x = dateTime, y = DO, color = 'black')) +
  geom_line(aes(x = dateTime, y = doPredic, color = 'red')) +
  scale_color_identity(guide = "legend",
                       name = 'Predictions',
                       labels = c("Observed", "Modeled")) +
  ylab('DO (mg/L)') +
  scale_x_datetime(date_labels = '%b', breaks = 'month') +
  theme_bw(base_size = 9) +
  theme(axis.title.x = element_blank())

# Plot the fluxes
p6 = ggplot(out.model_daily_sum) +
  geom_line(aes(x = date, y = npp/dt, color = 'green4')) +
  geom_line(aes(x = date, y = -Rtot/dt, color = 'red4')) +
  geom_line(aes(x = date, y = fatm/dt, color = 'black')) +
  scale_color_identity(guide = "legend",
                       name = 'Fluxes',
                       labels = c("Fatm", "NPP", "Rtot")) +
  ylab('DO (mg/L)') +
  scale_x_datetime(date_labels = '%b', breaks = 'month') +
  theme_bw(base_size = 9) +
  theme(axis.title.x = element_blank())

# Plot the cumulative fluxes
p7 = ggplot(out.model %>% slice(-1)) +
  geom_line(aes(x = dateTime, y = cumsum(npp), color = 'green4')) +
  geom_line(aes(x = dateTime, y = cumsum(-Rtot), color = 'red4')) +
  geom_line(aes(x = dateTime, y = cumsum(fatm), color = 'black')) +
  geom_line(aes(x = dateTime, y = cumsum(-Rtot + npp), color = 'darkslateblue')) +
  scale_color_identity(guide = "legend",
                       name = 'Cum. Fluxes',
                       labels = c("Fatm", "NEP", "NPP", "Rtot")) +
  ylab('DO (mg/L)') +
  scale_x_datetime(date_labels = '%b', breaks = 'month') +
  theme_bw(base_size = 9) +
  theme(axis.title.x = element_blank())

print(p5)
print(p6)
print(p7)

# Patchwork plots together
# p5 / p6 / p7 + 
#   plot_annotation(tag_levels = 'a', tag_suffix = ')') & 
#   theme(plot.tag = element_text(size = 8))



```


